export default async () => {
  let child = document.createElement("div");
  child.innerHTML = "-------------------------";
  document.getElementById("fetchWaterfall").appendChild(child);
  const title = document.createElement("div");
  title.innerHTML = "Example One - Async Load Without Promises";
  document.getElementById("fetchWaterfall").appendChild(title);
  await fetch(`static/trance1.m4a`);
  child = document.createElement("div");
  child.innerHTML = "1";
  document.getElementById("fetchWaterfall").appendChild(child);
  await fetch(`static/trance2.m4a`);
  child = document.createElement("div");
  child.innerHTML = "2";
  document.getElementById("fetchWaterfall").appendChild(child);
  await fetch(`static/trance3.m4a`);
  child = document.createElement("div");
  child.innerHTML = "3";
  document.getElementById("fetchWaterfall").appendChild(child);
  await fetch(`static/trance4.m4a`);
  child = document.createElement("div");
  child.innerHTML = "4";
  document.getElementById("fetchWaterfall").appendChild(child);
  fetch(`static/trance5.m4a`);
  child = document.createElement("div");
  child.innerHTML = "5";
  document.getElementById("fetchWaterfall").appendChild(child);
  await fetch(`static/trance6.m4a`);
  child = document.createElement("div");
  child.innerHTML = "6";
  document.getElementById("fetchWaterfall").appendChild(child);
  await fetch(`static/trance7.m4a`);
  child = document.createElement("div");
  child.innerHTML = "7";
  document.getElementById("fetchWaterfall").appendChild(child);
  await fetch(`static/trance8.m4a`);
  child = document.createElement("div");
  child.innerHTML = "8";
  document.getElementById("fetchWaterfall").appendChild(child);
  await fetch(`static/trance9.m4a`);
  child = document.createElement("div");
  child.innerHTML = "9";
  document.getElementById("fetchWaterfall").appendChild(child);
  const end = document.createElement("div");
  end.innerHTML = "-------------------------";
  document.getElementById("fetchWaterfall").appendChild(end);
};
